apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
          - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-master
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: db-user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: db-password
        volumeMounts:
          - name: wordpress-content
            mountPath: /var/www/html/wp-content
      volumes:
        - name: wordpress-content
          persistentVolumeClaim:
            claimName: wordpress-pv-claim
