filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

filebeat.modules:
- module: apache
  access:
    enabled: true
    var.paths: ["/var/log/INPUTS/apache/access.log*"]
  error:
    enabled: true
    var.paths: ["/var/log/INPUTS/apache/error.log*"]

- module: mysql
  error:
    enabled: true
    var.paths: ["/var/log/INPUTS/mysql/mysql_error.log*"]

- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/INPUTS/nginx/access.log*"]
  error:
    enabled: true
    var.paths: ["/var/log/INPUTS/nginx/web.error.log*"]

filebeat.inputs:

- type: filestream
  id: all
  enabled: true
  paths:
    -/var/log/INPUTS/*.log

processors:
  - add_docker_metadata: ~
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
setup.kibana:
  host: "kibana:5601"