metricbeat.config:
  modules:
    path: /usr/share/metricbeat/modules.d/*.yml
    reload.enabled: true

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: nginx
  enabled: true
  period: 10s
  metricsets: ["stubstatus"]
  hosts: ["http://nginx/metrics"]

- module: haproxy
  enabled: true
  period: 10s
  metricsets: ["stat"]
  hosts: ["http://haproxy:14567/stats)"]

- module: mysql
  enabled: true
  period: 10s
  metricsets: ["status"]
  hosts: ["root:password@tcp(db_master:3306)/"]

- module: apache
  enabled: true
  period: 10s
  metricsets: ["status"]
  hosts: ["http://wordpress_1/server-status)", "http://wordpress_2/server-status)", "http://wordpress_3/server-status)"]

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ['elasticsearch']

setup.kibana:
  host: "kibana:5601"

