global:
  scrape_interval: 15s
scrape_configs:
 
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 
 - job_name: elasticsearch
   static_configs:
     - targets:
         - "elasticsearch_exporter:9114"
 
 - job_name: 'load-balancer-metrics'
   static_configs:
    - targets: ['haproxy:8405']
 
 - job_name: 'webserver 1 metrics'
   static_configs:
    - targets: ['apache_exporter1:9117']
 
 - job_name: 'webserver 2 metrics'
   static_configs:
    - targets: ['apache_exporter2:9117']
 
 - job_name: 'webserver 3 metrics'
   static_configs:
    - targets: ['apache_exporter3:9117']

 - job_name: 'nginx metrics'
   static_configs:
    - targets: ['nginx_exporter:9113']

 - job_name: 'mysql metrics'
   static_configs:
    - targets: ['mysql_exporter:9104']
