apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
spec:
  serviceName: "mysql-slave"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: root-password
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_MASTER_HOST
            value: mysql-master
          - name: MYSQL_MASTER_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: root-password
        volumeMounts:
          - name: mysql-slave-storage
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-slave-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
